### ISSUE TITLE
Where is the "p" in N, r, p?

### ISSUE THREAD

**Issue by thinkloop** [dchest/scrypt-async-js#22]
Hey thanks for the lib! 

How come there is no param for `p` in the usual scrypt `N, r, p`?

For example, from the node.js reference implementation:

```
scrypt.hashSync(key,{"N":16,"r":1,"p":1},64,"")
```

https://github.com/barrysteyn/node-scrypt#test-vector-1

Thanks!

**Comment by dchest** [comment]
It's mentioned in README:

> **Limitation**
> Doesn't support parallelization parameter greater than 1.

Adding support for *p* would add a lot to the complexity of the async loop, so I just skipped it. It's useless in JavaScript anyway — the processing would be parallel, just like in the reference implementation, unless you support it via Web Workers, but since this library was meant to be compatible with older browsers, I couldn't rely on them.

That said, I'll accept pull request if someone implemented it.

**Comment by thinkloop** [comment]
OK, thanks for the reply.

I am trying to match the results with node reference implementation: https://github.com/barrysteyn/node-scrypt

But I am unable to get the same results, even with p = 1. Any idea what would be the equivalent of:
```
scrypt.hashSync(password, {"N":65536,"r":1,"p":8}, 32, salt)
```

**Comment by dchest** [comment]
Should be: logN = 16, r = 1

``
scrypt(password, salt, 16, 1, 32, callback)
```

(r = 1, BTW, is not good, should be 8 for now.)

**Comment by thinkloop** [comment]
That worked, thanks!

**Comment by evilaliv3** [comment]
@dchest from https://www.tarsnap.com/scrypt/scrypt.pdf "Note also that since the computations of SMix are independent, a large value of p can be used to increase the computational cost of scrypt without
increasing the memory usage"

it would be really valuable to have such a support in the library in order to be able too fine tune the algorithm properly;
in many use cases (when the library is used in the browser) the memory is really limited and capped by the general purpose compute and so logN cannot be set that big, and on such a condition one could benefit of adding some CPU complexity.

**Comment by dchest** [comment]
Yeah, I'd like to implement parallelization parameter one day, but this will happen in a new library I'm currently writing (although I'll probably accept a pull request). Here I just removed it for simplicity of implementation, as interrupted async loop is already crazy enough.

The thing is that each `p` is intended to load one CPU thread, so the proper implementation would use a web worker for each computation. (Although, even the reference implementation doesn't implement parallelization yet!) However, if we have access to web workers, we don't even need the complexity of `scrypt-async`, we can just make `scrypt` synchronous and put the whole scrypt computation into a web worker.

**Comment by thinkloop** [comment]
The ethereum blockchain requires p be over 1 for certain values, and web
workers will take a while for wide-spread support, there's a nice little
niche spot for single-threaded chunked variable p scrypt'ing. Just showing
a case for demand, not asking for free work :D. All the best.
